### ISSUE TITLE
Received Retained Messages are shown with label "NOT_RETAINED"

### ISSUE THREAD

**Issue by thagel** [EXXETA/correomqtt#156] opened 2023-07-18 07:46 UTC
When receiving retained messages "live" they are shown with the label "NOT RETAINED". After re-subscribing they are shown the correct way "RETAINED"

**Describe the solution you'd like**
Show retained messages with the label "RETAINED" always

**Describe alternatives you've considered**
or introduce a new label "INITIAL_RETAINED"

**Comment by farion** [comment] 2024-02-09 16:08
@thagel That works as intended.

Basically if a message is received live it is always "NOT RETAINED". Even if the message was sent with the retained flag. If a message is received caused by the fact that a client subscribed to a topic that contains retained messages those messages are marked as RETAINED. So the flag shows the reason why you received the message, not the flag that was used sending it.

**Closed as completed by farion** 2024-02-09 16:08 UTC
Labels: enhancement
